---
- hosts: harbor
  vars:
  - cpath: /data
  - version: v1.6.2
  - hapath: /data/harborHA 
  tasks: 
  - name: stop & rm registry
    docker_service:
      project_src: '{{ cpath }}/harbor'
      state: absent
      remove_volumes: true
  
  - name: clean registry directory
    file:
      path: '{{ item }}'
      state: absent
    with_items:
    - "/var/log/harbor"
    - "{{ hapath }}/ca_download"
    - "{{ hapath }}/config"
    - "{{ hapath }}/job_logs"
    - "{{ hapath }}/psc"
    - "{{ hapath }}/regisftry"
    - "{{ hapath }}/secretkey"
    - "{{ cpath  }}/harbor"

